### ISSUE TITLE
How can I add new latex packages? 

### ISSUE THREAD

**Issue by nil-is-lin** [quarto-journals/elsevier#11]
I tried to convert my previously written .tex file to .qmd, but some added packages, such as usepackage{bm}, I don't know which part of the .qmd file such code should be placed.

**Comment by dragonstyle** [comment]
Awesome! Typically, you would include these type of statements in the document header, using `include-in-header`. more here:

https://quarto.org/docs/output-formats/pdf-basics.html#latex-includes
