### ISSUE TITLE
Unable to use alternative bibliography styles

### ISSUE THREAD

**Issue by presnell** [quarto-journals/elsevier#13]
For one of the Elsevier medical journals I need a superscript numeric citation style, which presumably is supplied by both model3a-num-names.bst and model6-num-names.bst.  I have tried to enable this by downloading the bst files and adding biblio-style: model3a-num-names to the yaml header, as suggested in the template, but no matter what I try it seems that either elsearticle-num.bst or elsearticle-harv.bst is used. 

I have also tried adding natbiboptions: super, but this results in clash since this option is not recognized by either elsearticle-num.bst or elsearticle-harv.bst.

**Comment by dragonstyle** [comment]
Thanks for reporting this. It should be fixed as of `0.4.1` - you should be able to use the command `quarto update quarto-journals/elsevier` from your project directory  to get this latest version.

I tested using the front matter:

```markdown
format:
  elsevier-pdf:
    keep-tex: true
    journal:
      name: Journal Name
      formatting: preprint
      model: 3p
    biblio-style: model3a-num-names.bst
```

If you have a moment to check, I'd appreciate if you could check that this works (and particularly that the style of the references is as you'd expect for the BST file that you provide). 

Thanks for reporting this!
