### ISSUE TITLE
Switch to biblatex

### ISSUE THREAD

**Issue by raffaem** [quarto-journals/elsevier#28]
I'm having problems with the template for Elsevier: https://github.com/quarto-journals/elsevier/issues/27

My understanding is that the templates in this repo use natbib.

My other understanding is also that natbib is not actively developed anymore.

On the [CTAN natbib page](https://ctan.org/pkg/natbib?lang=en), the documentation is dated 2010.

The [natabib page on Overleaf](https://www.overleaf.com/learn/latex/Bibliography_management_with_natbib) recommends switching to biblatex.

> Note: If you are starting from scratch it's recommended to use [biblatex](https://www.overleaf.com/learn/latex/Bibliography_management_in_LaTeX) because that package provides localization in several languages, it's actively developed and makes bibliography management easier and more flexible. However, note that most journals still use bibtex and natbib.

Should we switch to biblatex?

**Comment by cderv** [comment]
> I'm having problems with the template for Elsevier: https://github.com/quarto-journals/elsevier/issues/27

This was not link to biblatex. It was an issue in our extension to pass the right options to elesevier class. 

> My understanding is that the templates in this repo use natbib.

Yes the elsevier template use natbib by default as the document class uses: http://mirrors.ctan.org/macros/latex/contrib/elsarticle/doc/elsdoc.pdf
So extension uses `cite-method: natbib`

A classoption can be set to opt-out natbib it seems, and in that case `cite-method` should be changed (https://quarto.org/docs/authoring/citations.html#sec-biblatex)

Note that our template also document using `cite-method: citeproc` to leverage Pandoc processing and CSL for style. 

So switching to biblatex is possible by the user through configuration. 

Hope it helps

**Comment by raffaem** [comment]
> > I'm having problems with the template for Elsevier: #27
> 
> This was not link to biblatex. It was an issue in our extension to pass the right options to elesevier class.
> 
> > My understanding is that the templates in this repo use natbib.
> 
> Yes the elsevier template use natbib by default as the document class uses: http://mirrors.ctan.org/macros/latex/contrib/elsarticle/doc/elsdoc.pdf So extension uses `cite-method: natbib`
> 
> A classoption can be set to opt-out natbib it seems, and in that case `cite-method` should be changed (https://quarto.org/docs/authoring/citations.html#sec-biblatex)
> 
> Note that our template also document using `cite-method: citeproc` to leverage Pandoc processing and CSL for style.
> 
> So switching to biblatex is possible by the user through configuration.
> 
> Hope it helps

Hello,

I cannot switch to any other citation engine (isthat how they are called?)

If I do
```
format:
  elsevier-pdf:
    cite-method: biblatex
```

I get:
```
ERROR: 
compilation failed- error
Package biblatex Error: Incompatible package 'natbib'.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.212 \blx@packageincompatibility
                                  

see paper.log for more information.
```

If I do:
```
ERROR: 
compilation failed- error
Package natbib Error: Bibliography not compatible with author-year citations.

(natbib)                Press <return> to continue in numerical citation style.


See the natbib package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.96 ...mand\NAT@force@numbers{}\NAT@force@numbers
                                                   

see paper.log for more information.
```

It only works with `cite-method: natbib`

**Comment by cderv** [comment]
This is because it needs to follow elsearticle class documentation too. 

As I said, `elsearticle` is using natbib by default. And you need to pass an option to avoid it. 

Did you try setting the `nonatbib` class option too ? 

> nonatbib To unload natbib.sty.

This is from the doc and can be set using 

````yaml
classoption: nonatbib
````

in YAML header. 

If this works ok, maybe there would be a way to set this automatically if `cite-method: biblatex` is set 🤔

**Comment by raffaem** [comment]
If I do:

```
format:
  elsevier-pdf:
    cite-method: biblatex
    classoption: noatbib
```

I get

```
Error running filter /opt/quarto/share/filters/main.lua:
..._PAPER/_extensions/quarto-journals/elsevier/elsevier.lua:28: attempt to index a nil value (field 'integer index')
stack traceback:
	..._PAPER/_extensions/quarto-journals/elsevier/elsevier.lua:40: in upvalue 'addClassOption'
	..._PAPER/_extensions/quarto-journals/elsevier/elsevier.lua:98: in function <..._PAPER/_extensions/quarto-journals/elsevier/elsevier.lua:59>
	[C]: in ?
	[C]: in method 'walk'
	/opt/quarto/share/filters/main.lua:557: in local 'checked_walk'
	/opt/quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:1334: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:1388: in function </opt/quarto/share/filters/main.lua:1385>
stack traceback:
	/opt/quarto/share/filters/main.lua:557: in local 'checked_walk'
	/opt/quarto/share/filters/main.lua:609: in function 'run_emulated_filter'
	/opt/quarto/share/filters/main.lua:1334: in local 'callback'
	[string "..."]:1888: in field 'withScriptFile'
	/opt/quarto/share/filters/main.lua:1350: in upvalue 'run_emulated_filter_chain'
	/opt/quarto/share/filters/main.lua:1388: in function </opt/quarto/share/filters/main.lua:1385>
```

**Comment by cderv** [comment]
Thanks. This is an issue because our Lua filter does not handle single text value. Usually there are several classoption and syntax is list. This would work 

````yaml
format:
  elsevier-pdf:
    cite-method: biblatex
    classoption: 
	  - nonatbib
````

or `classoption: [nonatbib]`


I'll fix this though to avoid bad error message

**Comment by raffaem** [comment]
No I get

```
ERROR: 
compilation failed- error
Undefined control sequence.
l.1253  \global\bibsep
                      =0pt 
```

**Comment by cderv** [comment]
This command definition is from elsevier class file. 

I really don't know if elsevier template is working correctly without natbib. It seems using biblatex creates problem. 

I think this should be checked without Quarto to see then how to adapt to make it work with this template. 

Currently the template works ok with natbib for sure. With biblatex it seems it needs adaptation.

This is not just bug fixing now, but really a matter for CTAN elsevier article compatibility with biblatex and their doc does not mention biblatex, so possibly this is not compatible.

**Comment by raffaem** [comment]
Related: https://tex.stackexchange.com/questions/321989/biblatex-instead-of-natbib-in-elsarticle-how

**Comment by cderv** [comment]
Thanks so it seems it is not possibly with tweak. 

It seems inserting 
```
\makeatletter
\let\c@author\relax
\makeatother
```

will remove the last error. 

Though maybe other will happen... Not sure that elsevier is supposed to be used with different than natbib. 

Anyhow, thanks for sharing the link !

**Comment by raffaem** [comment]
I wrote to ELS support.

They answered "nonatbib will work. Also you can use biblatex instead of natbib. This will currently work with preprint option only and not with other options like 3p, 5p, etc."

They'll update the github repo and look into the bug

**Comment by raffaem** [comment]
I don't think we are suposed to pass both `3p` and `preprint` to the class.

My understanding from [there](https://tex.stackexchange.com/a/502844/74382) and the [doc](https://ctan.mirror.garr.it/mirrors/ctan/macros/latex/contrib/elsarticle/doc/elsdoc.pdf) is that they are mutually exclusive

**Comment by cderv** [comment]
Thanks - let's remove from the template then.

**Comment by cderv** [comment]
even removing `3p`, we are left with the issue requiring 

```
\makeatletter
\let\c@author\relax
\makeatother
```

So let's wait for upstream update, and we'll update the template here.

**Comment by raffaem** [comment]
> even removing `3p`, we are left with the issue requiring
> 
> ```
> \makeatletter
> \let\c@author\relax
> \makeatother
> ```
> 
> So let's wait for upstream update, and we'll update the template here.

It now compiles correctly with elsarticle 3.4c

Although the `cite-style` option doesn't work as we don't put it in the biblatex options

**Comment by cderv** [comment]
> Although the cite-style option doesn't work as we don't put it in the biblatex options

Can you open a new issue on this please with example ? 

Thank you !

**Comment by raffaem** [comment]
> > Although the cite-style option doesn't work as we don't put it in the biblatex options
> 
> Can you open a new issue on this please with example ?
> 
> Thank you !

My new understanding of the matter is that `cite-style` is only relevant for `citeproc`citation engine, while we are supposed to use `biblatexoptions` if we use a `biblatex` citation engine

**Comment by cderv** [comment]
@lucas-johnson, what is "this" you are referring too ?

There were 

- initial discussion were I answered : https://github.com/quarto-journals/elsevier/issues/28#issuecomment-2360940596
- follow up comments with different topics. 

Please, in order to help us help you, open a new issue with clear updated information. It is ok to link to other opened issues, and usually more efficient than to comment on an old closed issue. Thank you !
