### ISSUE TITLE
install error on Mac

### ISSUE THREAD

**Issue by MarcellGranat** [quarto-journals/elsevier#4]
Hi,

 I tried to installed the extension as asked on Mac, but it returns a strange error:
on the terminal:
quarto install extension quarto-journals/article-format-template

And the answer is:
ERROR: Too many arguments: quarto-journals/article-format-template

Thanks for your help in advance

**Comment by dragonstyle** [comment]
Hmmm.. Sorry that you ran into this! I would expect you to use the following command:

`quarto install extension quarto-journals/elsevier`

If you use that command do you receive the same error?
