### ISSUE TITLE
multiple affiliations

### ISSUE THREAD

**Issue by maxlindmark** [quarto-journals/elsevier#6]
Hi, thanks for a nice template! Eager to try it out more. But is it possible to have multiple author affiliations in the elsevier journal format?

The following code for authors, as per [the guides on quarto](https://quarto.org/docs/journals/authors.html):

```{r}
author:
  - name: Norah Jones
    affiliations:
      - ref: cmu
      - ref: chicago
affiliations:
  - id: cmu
    name: Carnegie Mellon University
    city: Pittsburgh
    state: PA
  - id: chicago
    name: University of Chicago
    city: Chicago
    state: IL
```
gives the expected output when using the PLOS template:
<img width="738" alt="plos" src="https://user-images.githubusercontent.com/34577740/191251809-7d90e5af-ecce-48eb-8f37-f8b7d40b6760.png">

but not the elsevier one (I also note that elsevier produces a 1 instead of letters). 
<img width="417" alt="elsevier" src="https://user-images.githubusercontent.com/34577740/191251805-c23da082-d742-4027-9688-89cd18ed3355.png">

Could someone help me understand what is happening here?

**Comment by dragonstyle** [comment]
This looks like purely an error in the Elsevier template (also noting the problematic affiliation address format). I will try to take a closer look today and see if this is something that is straightforward to resolve!

**Comment by dragonstyle** [comment]
Ok I just pushed changes that should address this - the version is now 0.1.0. If you `quarto update extension quarto-journals/elsevier` where you're using it you should see the correct behavior now!

**Comment by mesfind** [comment]
_extensions/quarto-journals/elsevier/elsevier.lua:60: attempt to call a nil value (field 'cite_method')
