### ISSUE TITLE
`nil value (field 'cite_method')`

### ISSUE THREAD

**Issue by cgoo4** [quarto-journals/elsevier#7]
I have the latest versions of RStudio and quarto installed.

`quarto --version 1.1.251`

After creating a new quarto project in RStudio, running `quarto use template quarto-journals/elsevier` 

<img width="211" alt="image" src="https://user-images.githubusercontent.com/32419319/196525330-415c35b3-c747-4222-9383-593581054b86.png">

and then rendering (with the RStudio render button) the qt.qmd, I get the following error:

```
Error running filter _extensions/quarto-journals/elsevier/elsevier.lua:
_extensions/quarto-journals/elsevier/elsevier.lua:60: attempt to call a nil value (field 'cite_method')
```

**Comment by dragonstyle** [comment]
Could you try updating to the latest prerelease version of Quarto? We've been making changes to the LUA apis which have affected some of our formats...

https://quarto.org/docs/download/prerelease.html

**Comment by cgoo4** [comment]
Thank you. Yes, it's working with the pre-release `quarto --version 1.2.226`.
